// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/user.proto

package com.zanox;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:kafkatry.Notification)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string message_id = 1;</code>
     */
    boolean hasMessageId();
    /**
     * <code>required string message_id = 1;</code>
     */
    java.lang.String getMessageId();
    /**
     * <code>required string message_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <code>required string to_user = 2;</code>
     */
    boolean hasToUser();
    /**
     * <code>required string to_user = 2;</code>
     */
    java.lang.String getToUser();
    /**
     * <code>required string to_user = 2;</code>
     */
    com.google.protobuf.ByteString
        getToUserBytes();

    /**
     * <code>required string from_user_ = 3;</code>
     */
    boolean hasFromUser();
    /**
     * <code>required string from_user_ = 3;</code>
     */
    java.lang.String getFromUser();
    /**
     * <code>required string from_user_ = 3;</code>
     */
    com.google.protobuf.ByteString
        getFromUserBytes();

    /**
     * <code>optional string subject = 4;</code>
     */
    boolean hasSubject();
    /**
     * <code>optional string subject = 4;</code>
     */
    java.lang.String getSubject();
    /**
     * <code>optional string subject = 4;</code>
     */
    com.google.protobuf.ByteString
        getSubjectBytes();

    /**
     * <code>required string body = 5;</code>
     */
    boolean hasBody();
    /**
     * <code>required string body = 5;</code>
     */
    java.lang.String getBody();
    /**
     * <code>required string body = 5;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <code>required int64 sendOn = 6;</code>
     */
    boolean hasSendOn();
    /**
     * <code>required int64 sendOn = 6;</code>
     */
    long getSendOn();
  }
  /**
   * Protobuf type {@code kafkatry.Notification}
   */
  public static final class Notification extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:kafkatry.Notification)
      NotificationOrBuilder {
    // Use Notification.newBuilder() to construct.
    private Notification(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Notification(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Notification defaultInstance;
    public static Notification getDefaultInstance() {
      return defaultInstance;
    }

    public Notification getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Notification(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              messageId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              toUser_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              fromUser_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              subject_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              body_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              sendOn_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zanox.User.internal_static_kafkatry_Notification_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zanox.User.internal_static_kafkatry_Notification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zanox.User.Notification.class, com.zanox.User.Notification.Builder.class);
    }

    public static com.google.protobuf.Parser<Notification> PARSER =
        new com.google.protobuf.AbstractParser<Notification>() {
      public Notification parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Notification(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Notification> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MESSAGE_ID_FIELD_NUMBER = 1;
    private java.lang.Object messageId_;
    /**
     * <code>required string message_id = 1;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string message_id = 1;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          messageId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string message_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_USER_FIELD_NUMBER = 2;
    private java.lang.Object toUser_;
    /**
     * <code>required string to_user = 2;</code>
     */
    public boolean hasToUser() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string to_user = 2;</code>
     */
    public java.lang.String getToUser() {
      java.lang.Object ref = toUser_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toUser_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string to_user = 2;</code>
     */
    public com.google.protobuf.ByteString
        getToUserBytes() {
      java.lang.Object ref = toUser_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROM_USER__FIELD_NUMBER = 3;
    private java.lang.Object fromUser_;
    /**
     * <code>required string from_user_ = 3;</code>
     */
    public boolean hasFromUser() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string from_user_ = 3;</code>
     */
    public java.lang.String getFromUser() {
      java.lang.Object ref = fromUser_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromUser_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string from_user_ = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFromUserBytes() {
      java.lang.Object ref = fromUser_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBJECT_FIELD_NUMBER = 4;
    private java.lang.Object subject_;
    /**
     * <code>optional string subject = 4;</code>
     */
    public boolean hasSubject() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string subject = 4;</code>
     */
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          subject_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string subject = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 5;
    private java.lang.Object body_;
    /**
     * <code>required string body = 5;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string body = 5;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          body_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string body = 5;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDON_FIELD_NUMBER = 6;
    private long sendOn_;
    /**
     * <code>required int64 sendOn = 6;</code>
     */
    public boolean hasSendOn() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int64 sendOn = 6;</code>
     */
    public long getSendOn() {
      return sendOn_;
    }

    private void initFields() {
      messageId_ = "";
      toUser_ = "";
      fromUser_ = "";
      subject_ = "";
      body_ = "";
      sendOn_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSendOn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMessageIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getToUserBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFromUserBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSubjectBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getBodyBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, sendOn_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMessageIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getToUserBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFromUserBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSubjectBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getBodyBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, sendOn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zanox.User.Notification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zanox.User.Notification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zanox.User.Notification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zanox.User.Notification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zanox.User.Notification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zanox.User.Notification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zanox.User.Notification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zanox.User.Notification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zanox.User.Notification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zanox.User.Notification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zanox.User.Notification prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code kafkatry.Notification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:kafkatry.Notification)
        com.zanox.User.NotificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zanox.User.internal_static_kafkatry_Notification_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zanox.User.internal_static_kafkatry_Notification_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zanox.User.Notification.class, com.zanox.User.Notification.Builder.class);
      }

      // Construct using com.zanox.User.Notification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        toUser_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        fromUser_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        subject_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        body_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        sendOn_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zanox.User.internal_static_kafkatry_Notification_descriptor;
      }

      public com.zanox.User.Notification getDefaultInstanceForType() {
        return com.zanox.User.Notification.getDefaultInstance();
      }

      public com.zanox.User.Notification build() {
        com.zanox.User.Notification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zanox.User.Notification buildPartial() {
        com.zanox.User.Notification result = new com.zanox.User.Notification(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.toUser_ = toUser_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fromUser_ = fromUser_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.subject_ = subject_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.body_ = body_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sendOn_ = sendOn_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zanox.User.Notification) {
          return mergeFrom((com.zanox.User.Notification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zanox.User.Notification other) {
        if (other == com.zanox.User.Notification.getDefaultInstance()) return this;
        if (other.hasMessageId()) {
          bitField0_ |= 0x00000001;
          messageId_ = other.messageId_;
          onChanged();
        }
        if (other.hasToUser()) {
          bitField0_ |= 0x00000002;
          toUser_ = other.toUser_;
          onChanged();
        }
        if (other.hasFromUser()) {
          bitField0_ |= 0x00000004;
          fromUser_ = other.fromUser_;
          onChanged();
        }
        if (other.hasSubject()) {
          bitField0_ |= 0x00000008;
          subject_ = other.subject_;
          onChanged();
        }
        if (other.hasBody()) {
          bitField0_ |= 0x00000010;
          body_ = other.body_;
          onChanged();
        }
        if (other.hasSendOn()) {
          setSendOn(other.getSendOn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessageId()) {
          
          return false;
        }
        if (!hasToUser()) {
          
          return false;
        }
        if (!hasFromUser()) {
          
          return false;
        }
        if (!hasBody()) {
          
          return false;
        }
        if (!hasSendOn()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zanox.User.Notification parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zanox.User.Notification) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object messageId_ = "";
      /**
       * <code>required string message_id = 1;</code>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string message_id = 1;</code>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            messageId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string message_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string message_id = 1;</code>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string message_id = 1;</code>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>required string message_id = 1;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object toUser_ = "";
      /**
       * <code>required string to_user = 2;</code>
       */
      public boolean hasToUser() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string to_user = 2;</code>
       */
      public java.lang.String getToUser() {
        java.lang.Object ref = toUser_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            toUser_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string to_user = 2;</code>
       */
      public com.google.protobuf.ByteString
          getToUserBytes() {
        java.lang.Object ref = toUser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toUser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string to_user = 2;</code>
       */
      public Builder setToUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        toUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string to_user = 2;</code>
       */
      public Builder clearToUser() {
        bitField0_ = (bitField0_ & ~0x00000002);
        toUser_ = getDefaultInstance().getToUser();
        onChanged();
        return this;
      }
      /**
       * <code>required string to_user = 2;</code>
       */
      public Builder setToUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        toUser_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fromUser_ = "";
      /**
       * <code>required string from_user_ = 3;</code>
       */
      public boolean hasFromUser() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string from_user_ = 3;</code>
       */
      public java.lang.String getFromUser() {
        java.lang.Object ref = fromUser_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fromUser_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string from_user_ = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFromUserBytes() {
        java.lang.Object ref = fromUser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromUser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string from_user_ = 3;</code>
       */
      public Builder setFromUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fromUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string from_user_ = 3;</code>
       */
      public Builder clearFromUser() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fromUser_ = getDefaultInstance().getFromUser();
        onChanged();
        return this;
      }
      /**
       * <code>required string from_user_ = 3;</code>
       */
      public Builder setFromUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fromUser_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object subject_ = "";
      /**
       * <code>optional string subject = 4;</code>
       */
      public boolean hasSubject() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string subject = 4;</code>
       */
      public java.lang.String getSubject() {
        java.lang.Object ref = subject_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            subject_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string subject = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSubjectBytes() {
        java.lang.Object ref = subject_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string subject = 4;</code>
       */
      public Builder setSubject(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        subject_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string subject = 4;</code>
       */
      public Builder clearSubject() {
        bitField0_ = (bitField0_ & ~0x00000008);
        subject_ = getDefaultInstance().getSubject();
        onChanged();
        return this;
      }
      /**
       * <code>optional string subject = 4;</code>
       */
      public Builder setSubjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        subject_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>required string body = 5;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string body = 5;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            body_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string body = 5;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string body = 5;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string body = 5;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000010);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>required string body = 5;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        body_ = value;
        onChanged();
        return this;
      }

      private long sendOn_ ;
      /**
       * <code>required int64 sendOn = 6;</code>
       */
      public boolean hasSendOn() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 sendOn = 6;</code>
       */
      public long getSendOn() {
        return sendOn_;
      }
      /**
       * <code>required int64 sendOn = 6;</code>
       */
      public Builder setSendOn(long value) {
        bitField0_ |= 0x00000020;
        sendOn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sendOn = 6;</code>
       */
      public Builder clearSendOn() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sendOn_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:kafkatry.Notification)
    }

    static {
      defaultInstance = new Notification(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:kafkatry.Notification)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kafkatry_Notification_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_kafkatry_Notification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035src/main/resources/user.proto\022\010kafkatr" +
      "y\"v\n\014Notification\022\022\n\nmessage_id\030\001 \002(\t\022\017\n" +
      "\007to_user\030\002 \002(\t\022\022\n\nfrom_user_\030\003 \002(\t\022\017\n\007su" +
      "bject\030\004 \001(\t\022\014\n\004body\030\005 \002(\t\022\016\n\006sendOn\030\006 \002(" +
      "\003B\013\n\tcom.zanox"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_kafkatry_Notification_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kafkatry_Notification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_kafkatry_Notification_descriptor,
        new java.lang.String[] { "MessageId", "ToUser", "FromUser", "Subject", "Body", "SendOn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
